### PR TITLE
Fix stepper accessibility 

### LINKED ISSUE #44: Review Stepper component accessibility
Some research is needed with the Stepper component to see what is expected of these types of components and what gaps need filled when it comes to accessibility.

https://github.com/lifeomic/chroma-react/pull/43#pullrequestreview-543119239

### PR DESCRIPTION
**Pull request by HaleyWardo**
Closes #44 

**Issue**
- Visual impaired users have no way of know which step is the active step
- There are no focus styles when tabbing (we only have hover styles)
- Steps as `div` have no tabIndex so they are missed in the tab order

**Changes**
- Fixed syntax to be more semantic (`ol` & `li`) 
- Added focus styles to steps
- Added `tabIndex` to active `div` steps
  - Button steps already have a `tabIndex` with the button element
- Added `aria-label` to read active step index of out total number of steps
- Added `aria-describedBy` so screen readers can get title, subTitle, and subTitlePill values

**BEFORE**

https://user-images.githubusercontent.com/32574227/176944194-9135f19c-ca4b-464c-a36a-0dc948ea35bc.mov

**AFTER**

https://user-images.githubusercontent.com/32574227/176944173-af03c65f-dd6e-43a0-b25d-eccdfa76dd2c.mov

https://user-images.githubusercontent.com/32574227/176944179-5624733b-3203-4e88-a0e6-2213c972c54f.mov

### CODE REVIEW

File: src/components/Stepper/Step.tsx [hunk 1]
```diff
@@ -139,19 +150,37 @@ export const Step: React.FC<StepProps> = ({
...
+  index = 0,
+  numberOfSteps,
   onClick,
   subTitle,
   subTitlePillLabel,
   title,
   ...rootProps
 }) => {
   const classes = useStyles({});
+  const ariaLabel = `Step ${index + 1} of ${numberOfSteps}`;
```
Comment (smolster) [inline src/components/Stepper/Step.tsx:162]: Should numberOfSteps be required? It seems like otherwise, this will read "Step X of undefined"

Comment (HaleyWardo) [reply src/components/Stepper/Step.tsx:162]: The `numberOfSteps` prop is being passed in via the `Stepper` component when cloning the provided `Step`. We don't want to require this prop because then it would require all current implementations to pass it in. This is a prop that Chroma is controlling. Hopefully that makes sense.

Comment (HaleyWardo) [reply src/components/Stepper/Step.tsx:162]: We do the same with the `index` prop.

Comment (smolster) [reply src/components/Stepper/Step.tsx:162]: Does make sense -- thanks for the explanation.

**Review by smolster — APPROVED** [review]

**Review by xdumaine — APPROVED** [review]

**Comment by loscm** [comment]
Requested review from a random `@lifeomic/security` team member, @cfbevan, due to term: **access**.

This review is not blocking and is for broader awareness.  Consider if this change requires deeper security review and ask when it is necessary.

- [Automation](https://github.com/lifeomic/pr-security-flag-scanner/blob/master/src/lambdas/pr-security-flag-scanner/index.ts) | [#pr-flagged-sec-review](https://lifeomic.slack.com/messages/pr-flagged-sec-review)
