### PR TITLE
fix: Add `fullWidth` prop to `<RadioGroupMinimal`

### LINKED ISSUE #213: Add `fullWidth` prop to RadioGroupMinimal
`<RadioGroupMinimal` should not span 100% of parent's width by default. This is more noticeable when there are only two radio options.

Screen Shot 2021-11-03 at 9 55 14 AM

### PR DESCRIPTION
**Pull request by dexterca**
Adding `fullWidth` prop so that by default `<RadioGroupMinimal` doesn't span 100% width of parent. When there was only a couple of radio options, the design looked a little wonky on account of options being spread to extreme left and right when `direction` was set to `row`.

BEFORE | AFTER (default) | AFTER (fullWidth)
-- | -- | --
01-radio-min-before | 02-radio-min-after-default | 03-radio-min-fullWidth

**UPDATED DOCS**

Screen Shot 2021-11-03 at 11 23 42 AM

**UPDATED KNOBS**

`direction="row"` | `direction="column"`
-- | --
knob-row | knob-column

Closes #213

### CODE REVIEW

File: src/components/Radio/RadioGroupMinimal.tsx [hunk 1]
```diff
@@ -105,6 +106,11 @@ export const useStyles = makeStyles(
         },
       },
     },
+    radiosFullWidth: {
+      '& > div': {
```
Comment (dexterca) [inline src/components/Radio/RadioGroupMinimal.tsx:110]: Not sure this is the most elegant solution? 🤷🏻

File: stories/components/Radio/Radio.stories.tsx [hunk 2]
```diff
@@ -57,6 +57,7 @@ const getMinimalPropOptions = (): RadioGroupMinimalProps => {
       },
       'row'
     ),
+    fullWidth: boolean('fullWidth', false),
```
Comment (dexterca) [inline stories/components/Radio/Radio.stories.tsx:60]: Add `fullWidth` knob

**Review by ynotdraw — COMMENTED** [review]
Looks great to me! Only suggestion is adding a test to ensure the right classes get applied when adding the `fullWidth` prop.  Let me know if you need a hand!

**Comment by dexterca** [comment]
> Looks great to me! Only suggestion is adding a test to ensure the right classes get applied when adding the `fullWidth` prop. Let me know if you need a hand!

✅

**Review by ynotdraw — APPROVED** [review]
🎉

**Review by xdumaine — APPROVED** [review]

**Review by rob-snyder — APPROVED** [review]
