### PR TITLE
fix: Button height, icon shrink and text overflow

### LINKED ISSUE #230: Fix alignment of icons in buttons

### PR DESCRIPTION
**Pull request by dexterca**
This PR addresses the following various issues with buttons (including `<Button`, `<ButtonFilePicker`, `<ButtonLink` and `<MenuButton`):

1. Height: buttons would flex their height if parent was set to `display: flex`. This PR sets a max-height of `pxToRem(35)` to all buttons
2. Icon shrink: icons within buttons would shrink if there wasn't enough horizontal space to accommodate button text and icons
3. Text overflow: button text would overflow button container if there wasn't enough horizontal space. This PR adds `text-overflow: ellipsis` for buttons
4. `<ButtonLink` disabled state: disabled state styles for `<ButtonLink` now match other disabled buttons' styles

BEFORE | AFTER | &nbsp;
-- | -- | --
Screen Shot 2021-12-02 at 1 07 49 PM | Screen Shot 2021-12-02 at 1 07 22 PM | Icons no longer shrink and text overflows to ellipsis
Screen Shot 2021-12-02 at 1 14 05 PM | Screen Shot 2021-12-02 at 1 14 28 PM | Button height no longer flexes to parent height
Screen Shot 2021-12-02 at 1 18 17 PM | Screen Shot 2021-12-02 at 1 17 51 PM | Disabled state styles for `<ButtonLink` now match other buttons
Screen Shot 2021-12-02 at 1 31 15 PM | Screen Shot 2021-12-02 at 1 30 19 PM | Linked this PR to PHC

Closes #230

### CODE REVIEW

**Review by nicolls1 — APPROVED** [review]
Looks reasonable to me, maybe one more person could check as well 💯

File: src/components/Menu/MenuButton.tsx [hunk 1]
```diff
@@ -11,6 +11,9 @@ export const useStyles = makeStyles(
       width: theme.spacing(2),
       height: theme.spacing(2),
       marginLeft: theme.spacing(1),
+      verticalAlign: 'middle',
+      position: 'relative',
+      top: theme.pxToRem(-1),
```
Comment (xdumaine) [inline src/components/Menu/MenuButton.tsx:16]: Some of these are cryptic-ish, but I trust you 🤷🏽

**Review by xdumaine — APPROVED** [review]

**Review by ynotdraw — APPROVED** [review]

**Comment by ynotdraw** [comment]
Nice fixes, I think @AClineff brought up some of these before 👍
